name: onix_flutter_bricks
description: Onix Flutter Clean Architecture

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.4+29

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  window_manager: ^0.3.8
  recase: ^4.1.0
  process_run: ^0.14.1+3
  logger: ^2.0.2+1
  get_it: ^7.6.7
  file_selector: ^1.0.3
  msh_checkbox: ^2.0.1
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  http: ^1.2.0
  collection: ^1.18.0
  package_info_plus: ^5.0.1
  yaml: ^3.1.2
  url_launcher: ^6.2.4
  encrypt: ^5.0.3
  hive: ^2.2.3
  flutter_secure_storage: ^9.0.0
  loader_overlay: ^4.0.0
  dio: ^5.4.0
  retry: ^3.1.2
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  hive_flutter: ^1.1.0
  pretty_dio_logger: ^1.3.1
  fluttertoast: ^8.2.4
  go_router: ^13.1.0
  intl: ^0.19.0
  intl_utils: ^2.8.7
  dropdown_button2: ^2.3.9
  searchfield: ^0.9.0
  google_fonts: ^6.1.0
  flutter_styled_toast: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/platform_logo/
    - assets/documentation/
    - assets/signing/
    - assets/documentation/docs/
    - assets/documentation/docs/dev_solutions/
    - assets/fastlane/
    - assets/fastlane/android/
    - assets/fastlane/ios/
    - assets/git_cliff/

flutter_intl:
  enabled: true
  arb_dir: lib/core/app/localization/l10n
  output_dir: lib/core/app/localization/generated

#generated with mason
