name: onix_flutter_bricks
description: Onix Flutter Clean Architecture

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.15+15

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  window_manager: ^0.3.7
  recase: ^4.1.0
  process_run: ^0.13.2
  logger: ^2.0.2+1
  get_it: ^7.6.4
  file_selector: ^1.0.1
  msh_checkbox: ^2.0.1
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  http: ^1.1.0
  collection: ^1.17.0
  package_info_plus: ^4.2.0
  yaml: ^3.1.2
  url_launcher: ^6.2.1
  encrypt: ^5.0.3
  hive: ^2.2.3
  flutter_secure_storage: ^9.0.0
  loader_overlay: ^2.3.2
  dio: ^5.3.3
  retry: ^3.1.2
  connectivity_plus: ^5.0.1
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2
  dio_cache_interceptor: ^3.4.4
  dio_cache_interceptor_hive_store: ^3.2.1
  hive_flutter: ^1.1.0
  pretty_dio_logger: ^1.3.1
  fluttertoast: ^8.2.2
  go_router: ^12.1.0
  intl: ^0.18.1
  intl_utils: ^2.8.5
  dropdown_button2: ^2.3.9
  searchfield: ^0.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/platform_logo/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
  arb_dir: lib/core/app/localization/l10n
  output_dir: lib/core/app/localization/generated

#generated with mason